// Generated by nuxi
/// <reference types="@pinia/nuxt" />
/// <reference types="@nuxtjs/i18n" />
/// <reference types="@nuxtjs/tailwindcss" />
/// <reference types="@nuxtjs/google-fonts" />
/// <reference types="@nuxt/devtools" />
/// <reference types="@nuxt/telemetry" />

export {}
